#register:
#    path: /
##    controller: App\Controller\DefaultController::index
#    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#    defaults:
#        template: 'register.html.twig'
